### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by alejoroman0605**
## Fixed bug when uploading module to git.

Fixes #
I created a clean Solution Structure.
Added the user administration module to the Modules folder of the Solution Structure.

## Description
I created a clean Solution Structure and added the user management module to the Modules folder, this way the module compiles and generates the installer without any problems. The solution was created with the Upendo DNN Generator.

## How Has This Been Tested?

- I pushed the changes to git.
- I created a clean folder.
- Clone the repository back into the clean folder.
- I opened the code I compiled in debug mode, and in release mode.
- I installed it on a clean DNN solution.
- I tested how it works.

## Screenshots :

image
image

### CODE REVIEW

**Review by WillStrohl — CHANGES_REQUESTED** [review]
@alejoroman0605 This looks MUCH closer to what it originally should have been.  

The `.whitesource` file needs to stay.  
Why is there a `Resources/lib` folder in the root? 

@ismaelTartola Can you please help with this PR?

**Comment by alejoroman0605** [comment]
@WillStrohl The Resources/lib folder is in the root because I tried to use bootstrap local and finally used it online and the .whitesource file is not needed. Those files in the Fix-Bugs branch of my fork are missing, they remain only in the dev branch. It was a previous error when I uploaded the module the first time that it is already corrected in the Fix-Bugs branch.
image
image

**Comment by WillStrohl** [comment]
@alejoroman0605 I added `.whitesource` in PR #1. 

Is your PR going to remove those extra BS files?

**Comment by alejoroman0605** [comment]
@WillStrohl Yes the PR will remove those extra files.

**Comment by WillStrohl** [comment]
@alejoroman0605 Your PR is still deleting the `.whitesource` file.  That must remain in the project.

**Comment by alejoroman0605** [comment]
@WillStrohl I added .whitesource file.
image

**Review by WillStrohl — APPROVED** [review]
Approving - based on the comments here, and in Trello.

**Pull request merged**
