### PR TITLE
Modifications to show results of CreateUser, Issue #81 and fixed #83

### LINKED ISSUE #83: Create User - JavaScript has hard-coded values that should be coming from DNN
## Software Versions  
- DNN:  09.12.00  
- Module:  01.01.01  

## To Reproduce  
You can view the hard-coded values minLength and minNumberOfSpecialChars [here in Create.cshtml](https://github.com/UpendoVentures/Upendo-Dnn-UserManager/blob/eca38fee6c9c64c254af06238259ec3f15bc52d3/Modules/UserManager/Views/UserManage/Create.cshtml#L115)

## Expected behavior  
These values should be coming from DNN (set in web.config)

### PR DESCRIPTION
**Pull request by jeremy-farrance**
## Description
CreateUser was void, changed it to return Membership.UserCreateStatus

## How Has This Been Tested?
I was able to build and install the module. It works, but not well enough. It reports the error, but is a poor workflow causing the user to close the popup and start over.

I am also (so far) unsure if my change affects other parts of the code. 

## Screenshots (if appropriate):
image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project. (I think?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jeremy-farrance** [comment]
Updated the changes a little more so that the error properly display on the Create User popup via Validation Summary and Validation For.

**Comment by jeremy-farrance** [comment]
I am done for now until I get some feedback. Here is a recap of my proposed changes and improvements.
 
These are repeated in the added file, `releasenotes-10102.txt`

- **Create User now shows DNN Errors** - If clicking Save results in an error on the backend when DNN attempts to Create the new user and display that error in the popup Create User form. This prevents confusion (there was no indication the user was NOT created) and allows for correcting the problem without starting over.  (Issue #81)
- Removed code checking for duplicate Username and allowed it to happen on the backend (since we wired up the associated CreateUser error reporting)
- Removed the no longer used resource item; UsernameInUse
- Added CSS to style the per-field brief error messages (small, dark red)
- Cleaned up the JS @Localizations (added using)
- Client-side JavaScript was using hard-coded defaults for both password minLength and minNumberOfSpecialChars. Added calls to DNN's MembershipProviderConfig so these are now using the values from web.config (also tested this with JS disabled and CreateUser() properly catches this on the backend too)

**Review by WillStrohl — APPROVED** [review]
Looks great!

**Comment by WillStrohl** [comment]
Awesome stuff, @jeremy-farrance ... Thank you!

**Pull request merged**
